export const GET_DIAL_CODE = "GET_DIAL_CODE";
export const GET_DIAL_CODE_SUCCESS = "GET_DIAL_CODE_SUCCESS";
export const GET_DIAL_CODE_ERROR = "GET_DIAL_CODE_ERROR";

export const GET_PROJECT_LIST_FROM_ORG = "GET_PROJECT_LIST_FROM_ORG";
export const GET_PROJECT_LIST_FROM_ORG_SUCCESS =
  "GET_PROJECT_LIST_FROM_ORG_SUCCESS";
export const GET_PROJECT_LIST_FROM_ORG_ERROR = "GET_PROJECT_LIST_ERROR";

export const GET_RESOURCE_ROLE_LIST = "GET_RESOURCE_ROLE_LIST";
export const GET_RESOURCE_ROLE_LIST_SUCCESS = "GET_RESOURCE_ROLE_LIST_SUCCESS";
export const GET_RESOURCE_ROLE_LIST_ERROR = "GET_RESOURCE_ROLE_LIST_ERROR";

export const GET_ORG_LIST = "GET_ORG_LIST";
export const GET_ORG_LIST_SUCCESS = "GET_ORG_LIST_SUCCESS";
export const GET_ORG_LIST_ERROR = "GET_ORG_LIST_ERROR";
