export const GET_VEHICLE_TRIP_REPORTS = "GET_VEHICLE_TRIP_REPORTS";
export const GET_VEHICLE_TRIP_REPORTS_SUCCESS =
  "GET_VEHICLE_TRIP_REPORTS_SUCCESS";
export const GET_VEHICLE_TRIP_REPORTS_ERROR = "GET_VEHICLE_TRIP_REPORTS_ERROR";
