export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const GET_PROJECT_MGMT = "GET_PROJECT_MGMT";
export const GET_PROJECT_MGMT_SUCCESS = "GET_PROJECT_MGMT_SUCCESS";
export const GET_PROJECT_MGMT_ERROR = "GET_PROJECT_MGMT_ERROR";

export const ADD_PROJECT_MGMT = "ADD_PROJECT_MGMT";
export const ADD_PROJECT_MGMT_SUCCESS = "ADD_PROJECT_MGMT_SUCCESS";
export const ADD_PROJECT_MGMT_ERROR = "ADD_PROJECT_MGMT_ERROR";

export const EDIT_PROJECT_MGMT = "EDIT_PROJECT_MGMT";
export const EDIT_PROJECT_MGMT_SUCCESS = "EDIT_PROJECT_MGMT_SUCCESS";
export const EDIT_PROJECT_MGMT_ERROR = "EDIT_PROJECT_MGMT_ERROR";

export const DELETE_PROJECT_MGMT = "DELETE_PROJECT_MGMT";
export const DELETE_PROJECT_MGMT_SUCCESS = "DELETE_PROJECT_MGMT_SUCCESS";
export const DELETE_PROJECT_MGMT_ERROR = "DELETE_PROJECT_MGMT_ERROR";
