const routes = {
  DASHBOARD: "/",
  SA_AS_EVENT: "/sA-ASEvents",
  HIGH_EVENT: "/highEvents",
  LOW_EVENT: "/lowEvents",
  REQUESTED_VIDEO: "/requestedVideo",
  GEO_FENCE_EVENT: "/geo-FenceEvents",
  PANIC_BUTTON_EVENT: "/panicButtonEvents",
  DRIVER_STATISTIC: "/driverStatistics",
  VEHICLE_TRIP: "/vehicleTrip",
  GEO_FENCING: "/geoFencing",
  MAPS: "/maps",
  EVENTS_REPORT: "/eventReport",
  VIDEO_REQUEST_REPORT: "/videoRequestReport",
  DEVICE_REPORT: "/deviceReport",
  ORGANIZATION_REPORT: "/organizationReport",
  VEHICLE_TRIP_REPORT: "/vehicleTripReport",
  MANAGE_ROLES: "/manageRoles",
  USERS_MANAGEMENT: "/usersManagement",
  PROJECT_MANAGEMENT: "/projectManagement",
  SUPPORT_TICKET: "/supportTicket",
  DRIVER_MANAGEMENT: "/driverManagement",
  DEVICE_MANAGEMENT: "/deviceManagement",
  DEVICE_STATUS: "/deviceStatus",
  ARCHIVE: "/archive",
  LOGOUT: "/logout",
  GLOBAL_SEARCH: "/globalSearch",
  USER_CONFIGURATION: "/userConfiguration",
  HIGH_EVENTS_VIDEO: "/highEventsVideo",
  ADD_CONFIGURATION: "/addConfiguration",
  EDIT_CONFIGURATION: "/editConfiguration",
  COMMON_CONFIGURATION: "/commonConfiguration",
  COMMON_CONFIG: "/commonConfig",
  TRIPS_DETAIL: "/tripsDetail",
  DRIVER_SCORE_CARD: "/driverScoreCard",
};

export const ROUTES = routes;
